apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
  - name: nginx
    newName: nginx
    newTag: 1.17.0
commonAnnotations:
  kubernetes.io/change-cause: "Image updated to 1.17.0"